//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsolidadoEficienciaFisica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConsolidadoEficienciaFisica()
        {
            this.EficienciaFisica = new HashSet<EficienciaFisica>();
        }
    
        public int Id { get; set; }
        public int Edad { get; set; }
        public string Genero { get; set; }
        public int CantidadAlumnos { get; set; }
        public Nullable<decimal> PromedioPeso { get; set; }
        public Nullable<int> PromedioTalla { get; set; }
        public Nullable<decimal> PromedioVelocidad { get; set; }
        public Nullable<decimal> PromedioResistencia { get; set; }
        public Nullable<int> PromedioSalto { get; set; }
        public Nullable<int> PromedioPechadas { get; set; }
        public Nullable<int> PromedioAbdominales { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime FechaConsolidado { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public bool Activo { get; set; }
        public int SemestreId { get; set; }
        public int AñoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EficienciaFisica> EficienciaFisica { get; set; }
        public virtual Semestre Semestre { get; set; }
        public virtual Año Año { get; set; }
    }
}
