//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlMerienda
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public int AsistenciaEsperadaMujeres { get; set; }
        public int AsistenciaEsperadaTotal { get; set; }
        public Nullable<int> AsistenciaRealMujeres { get; set; }
        public int AsistenciaRealTotal { get; set; }
        public decimal EAceite { get; set; }
        public decimal EArroz { get; set; }
        public decimal ECereal { get; set; }
        public decimal EFrijoles { get; set; }
        public decimal EMaiz { get; set; }
        public string FirmaDocente { get; set; }
        public string CedulaTutor { get; set; }
        public string FirmaTutor { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public bool Activo { get; set; }
        public int CursoAcademicoId { get; set; }
        public int InventarioAlimentoId { get; set; }
        public int InventarioAlimentoId2 { get; set; }
        public int InventarioAlimentoId1 { get; set; }
        public int InventarioAlimentoId3 { get; set; }
        public int InventarioAlimentoId4 { get; set; }
        public int InventarioAlimentoId5 { get; set; }
        public int EstudianteId { get; set; }
    
        public virtual CursoAcademico CursoAcademico { get; set; }
        public virtual InventarioAlimento RAceite { get; set; }
        public virtual InventarioAlimento RArroz { get; set; }
        public virtual InventarioAlimento RCereal { get; set; }
        public virtual InventarioAlimento RFrijoles { get; set; }
        public virtual InventarioAlimento RMaiz { get; set; }
        public virtual Estudiante Estudiante { get; set; }
    }
}
