//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioAlimento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventarioAlimento()
        {
            this.ControlMerienda = new HashSet<ControlMerienda>();
            this.ControlMerienda1 = new HashSet<ControlMerienda>();
            this.ControlMerienda2 = new HashSet<ControlMerienda>();
            this.ControlMerienda3 = new HashSet<ControlMerienda>();
            this.ControlMerienda4 = new HashSet<ControlMerienda>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string NombreAlimento { get; set; }
        public decimal Stock { get; set; }
        public string UnidadDeMedida { get; set; }
        public System.DateTime FechaReabastecimiento { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlMerienda> ControlMerienda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlMerienda> ControlMerienda1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlMerienda> ControlMerienda2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlMerienda> ControlMerienda3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlMerienda> ControlMerienda4 { get; set; }
    }
}
