//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public bool Continuidad { get; set; }
        public bool Traslado { get; set; }
        public bool Repitente { get; set; }
        public string FechaMatricula { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public bool Activo { get; set; }
        public int EstudianteId { get; set; }
        public int TutorId { get; set; }
        public int PeriodosId { get; set; }
        public int AñoAcademicoId { get; set; }
        public bool Aprobado { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Tutor Tutor { get; set; }
        public virtual Periodo Periodos { get; set; }
        public virtual AñoAcademico AñoAcademico { get; set; }
    }
}
